### ISSUE TITLE
--missing-cutoff -c for population with <5% admixture

### ISSUE THREAD

**Issue by MrLocuace** [popgenmethods/smcpp#126]
Hello Jonathan,
I have 2 human populations (~4,000,000 SNPs; n ~50; genome coverage ~5X) that have <5% admixture from a third population. Admixture took place ~300 years ago. I have a few questions:

1. I cannot mask these segments so I am thinking in using --missing-cutoff. However, I am not sure what approximate value of -c (bp of runs of homozgosity) should I use. 

2. I am thinking in just using individuals with <2% admixture, but then I would end up with ~10 individuals in each population. What is the minumim n that can be used to obtain reliable results (e.g. Ne, split time)?

3. I want to compute the Ne trajectory of these populations over time. smc++ computes Ne for individual chromosomes. How can I combine Ne of the 22 autosomes to get a single Ne instead of 22 Nes?

Thank you very much in advance
All the best

**Comment by terhorst** [comment]
In order:

1. If I understand you correctly, you are saying you can't mask out the introgressed tracts? This is not something that could be handled by `-c` since indeed, you won't see long RoH here. My best suggestion would be to try and call the tracts using another method, and then generate a mask based on that.

2. We have some plots in our paper that show the effect of varying the sample size, but they don't include admixture. I'd recommend simulating data under a model that approximates the demography of your population(s) in order to get a sense of what is feasible.

3. Pass all of the chromosomes in as options for a single run of `smc++ estimate`.
