### ISSUE TITLE
anaconda install error

### ISSUE THREAD

**Issue by edgarjavi** [popgenmethods/smcpp#13]
Hi,

I am trying to install SMC using the anaconda installation steps but I think there are compatibility issues with python 3.6 and smcpp.

I get this error

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - smcpp

Thanks

Edgar Hernandez

**Comment by terhorst** [comment]
The latest versions of Anaconda Python now ship with 3.6, which creates dependency problems since a lot of packages have yet to be rebuilt for py36. For now I have locked the Python version of the smcpp conda package to 3.5 which should solve the problem. I will add 3.6 support once all the necessary dependencies have been updated.
