### ISSUE TITLE
smc++ c v error saying need to specify --folds

### ISSUE THREAD

**Issue by rozaimirazali** [popgenmethods/smcpp#133]
![Screen Shot 2019-12-05 at 9 18 54 AM](https://user-images.githubusercontent.com/37179568/70209097-6353bf00-1740-11ea-9ee8-92dfa2f0ed7d.png)

I am trying to run the cv but I am getting an error message saying I need to specify --folds ?

My command is: 

`smc++ cv --cores 32 -o ../output/cv/ --base F4.15 1.2e-8 ../output/vcf2smc/chr15.F4.smc.gz`

The input file to smc++ cv - ../output/vcf2smc/chr15.F4.smc.gz - was generated using the following command:

`smc++ vcf2smc --cores 32 --mask ../input/hs37d5_chr15.mask.bed.gz ../input/chr15.vcf.gz ../output/vcf2smc/chr15.F4.smc.gz 15 F4:X1,X2,X3,X4,etc`

I am confused. What actually I need to put in --folds ? a value between 2 to 15 ?

**Comment by pstokespmb** [comment]
The problem does not seem to be the number of folds you are specifying necessarily. The likely problem is because each smc.gz file is treated as a contig. You are choosing to set the kfolds parameter to an integer larger than the number of contigs supplied. There are simply not enough input smc.gz files to satisfy the kfolds parameter.

Your input should be chr01.smc.gz chr02.smc.gz chr03.smc.gz chr04.smc.gz [......] chr[n].smc.gz.

**Comment by terhorst** [comment]
@pstokespmb is correct. Marking as resolved.

**Comment by lczech** [comment]
I just ran into the same issue, because unfortunately, the documentation was a bit confusing with respect to this. From reading the README, it was at first not obvious to me which subcommands expect which exact files. 

In particular, my confusion is/was as follows:
 - `vcf_to_smc`: As far as I understood this, that command has to be called separately for each population and for each contig, and furthermore HAS to be called multiple times with a couple of different "distinguished individuals", as otherwise one runs unto the issue that @rozaimirazali explained above. This was not clear to me - in particular as the `-d` option to specify the distinguished individual is optional. This makes it seem that using that option is not needed at all...
 - `estimate`/`cv`: This command then has to be called for each population individually (which makes sense, as we want their respective demographic histories), and for each call takes all the files from above for all contigs and for all distinguished individuals of the given population. That is at least what I think is needed - is that right? The documentation just states that `<data file> [<data file> ...]` are needed, but that does not clarify which ones are needed for one call of the command. 

The way I explained it seems to be the only way that makes sense (I think - please correct me if I'm wrong), but still, juggling around with all these files while being new to the field, it took me a bit to figure this out. A bit more detail in the documentation, or a full working example with resulting plot would greatly be appreciated! Right now, the examples given for each subcommand do not reflect a full workflow with the [exemplary data](https://github.com/popgenmethods/smcpp/tree/master/example). @terhorst, what do you think?

Thanks in advance
Lucas

**Comment by pstokespmb** [comment]
I think you are mostly correct about some of the assumptions of the vcf2smc command. I think it is important to remember that there are two major aspects of this command that are really important for moving on to estimate/cv. First, the -d option CAN specify different samples, but the reason for specifying the same sample is for heterozygosity. If two different samples are selected, then there is no differentiation between heterozygotic loci. This is really important for running vcf2smc on many samples, as you may not need to run vcf2smc on every combination or pair of samples as distinguished individuals. 

Your point about estimate/cv seems correct to me. The file input for estimate/cv are the .smc.gz files generated from vcf2smc. I think a common mistake that is made with regards to cv is the specification of folds. k-fold cross validation is a machine learning type thing. So lets say you have a species that has 9 chromosomes. If you run vcf2smc with just 1 sample (specifying -d as sample1 sample1), you will have 9 .smc.gz files. You wouldnt be able to specify 10 k-folds as an example. A k-fold specification of say 3 would be more appropriate. 

I found that generally, I use estimate for semi-robust analysis. I realize that CV is the best way to go for publication, but it takes much longer and requires more computational power. So I use estimate until I am satisfied with the plot and ready to commit to more runtime.

**Comment by lczech** [comment]
Thanks, @pstokespmb, for the insight! 

I am not completely sure whether I got your point about when I have to use two different samples with vcf2smc. For now, I used the same sample twice in `-d`, and run the `vcf2smc` command ~10 times with different samples. I hope that this is what is needed.

The tip with using `estimate` first is a good idea, I'll try that!
