### ISSUE TITLE
RuntimeError: erroneous average coalescence time

### ISSUE THREAD

**Issue by rozaimirazali** [popgenmethods/smcpp#135]
![Screen Shot 2019-12-05 at 9 55 30 AM](https://user-images.githubusercontent.com/37179568/70211153-79b04980-1745-11ea-9776-4818d14e9c58.png)

For some of my population, I am facing the above issue, which is different from a population with larger sample size  https://github.com/popgenmethods/smcpp/issues/134#issue-533160743

My command is:

`smc++ estimate --cores 32 -o ../output/estimate/ --base PJL.15 1.25e-8 ../output/vcf2smc/chr15.PJL.smc.gz`

The above image is output from the stderr. For the output from the stdout, please see the below image

![Screen Shot 2019-12-05 at 10 50 46 AM](https://user-images.githubusercontent.com/37179568/70214809-1f1aeb80-174d-11ea-8546-75ca45ad301a.png)

What could cause the error ?

**Comment by terhorst** [comment]
Per the warning message, you have a run of homozygosity of length 20Mb in your data (1/5th of the overall sequence length). The estimated coalescence time in that region will be numerically zero. Please see the FAQ for further information.

**Comment by rozaimirazali** [comment]
Thanks but my population is highly inbred. In this case, if i were to apply a strict -m or -c during vcf2smc, would it not get rid of this real signal ? do you have any suggestions other than -m or -c ?

Thanks

**Comment by terhorst** [comment]
If your population is highly inbred, then there are fundamental theoretical limits to what you can hope to infer about size history. Events that happened more anciently than the lifetime of the most recent common ancestor of your sample are effectively invisible. This is in essence why the program is crashing: it estimates that the recent effective population size of your population is near zero, which is just another way of saying that inbreeding levels are quite high. So, they answer it's giving you is not wrong, although ideally it would produce a more informative error message rather than crash. To your question about signal, I strongly advocate simulating data under a model that mimics the level of inbreeding in your sample in order to understand the extent to which the data distribution varies as a function of the size history features you are attempting to infer.
