### ISSUE TITLE
[Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by ariloytynoja** [popgenmethods/smcpp#141]
Hi again,

I have problems installing the latest version of smc++ and I tested the version "smcpp-1.15.2-Linux-x86_64.sh". It seems to start fine but all the runs quit with an error similar to this:

```
2383444 smcpp.optimize.plugins.progress_printer INFO Current model:

 3.38  2.61  2.19  1.81
29.28 28.82 28.36 27.92 27.48 27.04 26.62 26.20 25.79 25.38 24.98 24.59 24.20 23.82 23.44 23.07 22.71 22.35 22.00 21.65 21.31 20.98 20.65 20.32 20.00 19.69 19.38 19.07 18.77 18.47 18.18 17.90 17.61 17.34 17.06 16.80 16.53 16.27 16.01 15.76 15.51 15.27 15.03 14.79 14.56 14.33 14.10 13.88 13.66 13.45 13.24 13.03 12.82 12.62 12.42 12.23 12.03 11.85 11.66 11.48 11.29 11.12 10.94 10.77 10.60 10.43 10.27 10.11  9.95  9.79  9.64  9.49  9.34  9.19  9.04  8.90  8.76  8.62  8.49  8.35  8.22  8.09  7.97  7.84  7.72  7.60  7.48  7.36  7.24  7.13  7.02  6.91  6.80  6.69  6.59  6.48  6.38  6.28  6.18  6.08
2383445 smcpp.data_filter INFO Loading data...
2385011 smcpp.analysis.analysis WARNING Mixture model failed for setting hidden states. Error was: [Errno 12] Cannot allocate memory
```

I can't believe that the RAM would be the real issue. I'm analysing 10 contigs for four individuals, the gz-files totalling 3.2M. At an earlier point, the output has these lines.

```
730 smcpp.data_filter INFO Loading data...
2606 smcpp.data_filter INFO 0.08 Gb of data
```

My system has 340G of RAM.

Thanks in advance!

Regards, Ari

**Comment by terhorst** [comment]
Hrm, yes, "[340G ought to be enough for anyone](https://quoteinvestigator.com/2011/09/08/640k-enough/)" :-) I introduced an experimental method for tuning the hidden states. It's failing here, I think because it's trying to fit a mixture model with a lot of hidden states: https://github.com/popgenmethods/smcpp/blob/b64a6fdd453248cb4773523de91ed2eb139cf5a3/smcpp/analysis/analysis.py#L144 I'll look into ways to make it more robust. If the heuristic fails, the program should still fall back gracefully to picking hidden states the old way, so you should still be able to run it without problems.

**Comment by ariloytynoja** [comment]
Thanks. I suppose I need to get the latest version working.
