### ISSUE TITLE
Population curve not-consistent

### ISSUE THREAD

**Issue by Anahit19** [popgenmethods/smcpp#154]
Hi,

Just a very quick question, I apologize again.

I wanted to repeat the SMC++ analysis with Sardinian population and was following the same parameters used in the paper https://science.sciencemag.org/content/367/6484/eaay5012.full (--knots 10 --t1 150). I took 5 WG samples of Sardinians from HGDP panel. Then I was thinking to calculate split time between my populations and Sardinians.

The issue is that my curves for Sardinians and my populations are quite similar and they go sharply down (attached), while as I see from the results in the papers (attached), it the population sizes should be around 10000-100000. What could be the problem? I have double-checked my data and I did not find any issue.

Thanks a lot!!

![Sardinia](https://user-images.githubusercontent.com/53218207/81721207-9721d600-9490-11ea-89dc-05a841016fee.PNG)
![plot_150generations_10knots](https://user-images.githubusercontent.com/53218207/81721691-52e30580-9491-11ea-89a1-f4b76f919901.png)

**Comment by aabiddanda** [comment]
Hi @Anahit19 - I hope that this finds you well. I ran the original SMC++ analysis in the Sardinia Nature Genetics paper you cited above. I have the following concerns regarding trying to compare the analyses:

1. I think that the difference in sample size (24 WGS vs. 4 high-coverage + 90 low-coverage) does make a substantial difference in the extent that you can leverage the local SFS for the inference of recent demography. I think that it makes it much more difficult to compare between the HGDP paper and our results. I would suggest trying to replicate [figure 5A in the Bergstrom paper](https://science.sciencemag.org/content/sci/367/6484/eaay5012/F5.large.jpg) by trying the following:

- a. Setting the most recent time to be inferred as 1000 generations
- b. Taking the composite likelihood over 6 different distinguished lineages if possible

2. This is a hunch, but it might be worth applying a mappability mask and excluding centromeres as well. What I had done was to (1) apply a mask to the VCF file itself (via bcftools) and (2) exclude stretches longer than a megabase with no variation at all (the `-c` flag in `smc++ vcf2smc`) 
I know that I had to when running my original analysis and I also remember emailing with J.Terhorst s and he gave me the hint that one should try to remove the centromeres because otherwise they will be treated as long runs of homozygosity and drag the recent population-size down like it does above. Feel free to email me at at abiddanda [at] uchicago.edu if you have any more specific questions!

**Comment by Anahit19** [comment]
Hi @aabiddanda 

Many thanks for your kind assistance with this issue ! It is very helpful!

Best,
Anahit
