### ISSUE TITLE
How does sample size affect results

### ISSUE THREAD

**Issue by JiangYuLab** [popgenmethods/smcpp#30]
Dear @terhorst

I compared the Ne results from from different sample size in one population, the result is different in the recent past.

the result with all about 160 individuals
![ll](https://user-images.githubusercontent.com/28444574/27436313-673718ea-5791-11e7-9c0a-9e85f56a6f2f.png)

the result with a sub set of 40 individuals
![ll](https://user-images.githubusercontent.com/28444574/27436344-7e824600-5791-11e7-855c-c080c2bad4ba.png)

So I want to know how many individuals required when we want to know the recent population history?

Many thanks.
Best
Zhuqing

**Comment by terhorst** [comment]
I don't have a precise (theoretical) answer to this question, but I recommend parametric bootstrap to assess uncertainty in the recent past as a function of sample size. BTW do you have long runs of homozygosity in your data? I have encountered crashes in Ne in in the recent with large sample sizes due to this. It's usually because there are uncalled (missing) sites in sequence data which are not marked as such in the VCF.

**Comment by JiangYuLab** [comment]
Dear @terhorst 

Thanks. I have masked the regions with large uncalled (Here, I also wonder to know whether the BED file is 0-based?). So I think I can do bootstrap to assess this with randomly selected individuals. Is this ok or can i use some other methods or genetic parameters to to this? 

Best
Zhuqing

**Comment by terhorst** [comment]
The BED file should be 1-based although we're talking about masking out a single base pair here so practically speaking it makes no difference. You can bootstrap with random individuals or by breaking up the genome into small chunks and resampling, which has the advantage of keeping the sample size the same.
