### ISSUE TITLE
Python 3.X support

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [popgenmethods/smcpp#32]
I'm trying to install your package and conda is complaining it's not compatible with Python 3.6. Your readme lists the Python requirement as 3.3 or greater and I'm wondering which is correct.

**Comment by terhorst** [comment]
Both are correct. The package builds and runs fine on Python 3.3+. At the moment I only distribute precompiled conda binaries for py35 -- when I tried building SMC++ binaries a couple of months ago under Conda 4.3/py36, there were a lot of problems due to not all of SMC++'s dependencies having pushed py36 variants yet. I'll look into re-enabling it.
