### ISSUE TITLE
smc++ huge virtual memory bug

### ISSUE THREAD

**Issue by songli-bgi** [popgenmethods/smcpp#34]
Hi jonathan,
I run smc++ with command estimate for effect population size of human species. Now, my detail setting are:
gcc version 4.4.7
python 3.5
mpfr 1.2.0
gmp 3.5.0
I use conda to install smc++, while my GLIBC-2.14 was not available, so I downloaded and complied GLIBC-2.14, and use it with LD_PRELOAD.

All output with -v option was stored in this file, please download it with the link:
[https://pan.genomics.cn/ucdisk/s/3qMBfi](https://pan.genomics.cn/ucdisk/s/3qMBfi)
I think the problem is maybe caused by differenct version of **mutliprocess** or **concurrent** libraries. 

Best,
Song Li

**Comment by terhorst** [comment]
The log file looks normal. I am pretty sure that the problem is due to linking in GLIBC_214 at runtime. There is no way to safely do this. Please see the [FAQ](https://github.com/popgenmethods/smcpp#frequently-asked-questions). You'll need to build the software yourself, or find a system that has a modern version of glibc installed. Thanks,

Jonathan
