### ISSUE TITLE
error when using vcf2smc

### ISSUE THREAD

**Issue by guzhongru** [popgenmethods/smcpp#8]
Hi Jonathan
When I using the 'smc++ vcf2smc' command, there is an error appeared. Can you please told me how can I solve this.

Here is my vcf file

```
##fileformat=VCFv4.2
##source=fcGENE
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##contig=<ID=1,length=30000000>
##FILTER=<ID=PASS,Description="Passed variant FILTERs">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	RUSP10	RUSP11	RUSP12	RUSP13	RUSP14	RUSP15	RUSP16	RUSP17	RUSP18	RUSP19	RUSP1	RUSP20RUSP21	RUSP22	RUSP23	RUSP24	RUSP25	RUSP26	RUSP27	RUSP28	RUSP29	RUSP2	RUSP30	RUSP3	RUSP4	RUSP5	RUSP6	RUSP7	RUSP8	RUSP9
Chr12	2237	Chr12_2237	A	T	.	PASS	AF=0.55	GT	0/1	0/0	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	1/1	0/1	1/1	1/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	1/1	0/1
Chr12	2244	Chr12_2244	G	C	.	PASS	AF=0.3	GT	1/0	1/0	1/0	1/0	0/0	1/0	1/0	0/0	0/0	0/0	1/0	0/0	0/0	0/0	0/0	0/0	1/0	0/0	1/0	1/0	1/0	1/0	0/0	1/0	1/0	1/0	1/0	1/0	0/0	1/0
Chr12	2259	Chr12_2259	A	G	.	PASS	AF=0.35	GT	0/1	0/1	0/1	0/1	0/0	0/1	0/1	0/0	0/1	0/0	0/1	0/0	0/1	0/0	0/0	0/1	0/1	0/0	0/1	0/1	0/1	0/1	0/0	0/1	0/1	0/1	0/1	0/1	0/0	0/1
```

and then I used the 'bgzip input.vcf' and 'tabix -p vcf input.vcf.gz' build an indexed file. But when I using the 'smc++ vcf2smc -v input.vcf.gz input.smc.gz Chr12 RUSP1:RUSP1,RUSP2' command, an error appeared.

```
8578 smcpp.logging DEBUG SMC++ v1.6.2.dev0+nge57e612.d20170203
8578 smcpp.commands.vcf2smc WARNING Neither missing cutoff (-c) or mask (-m) has been specified. This means that stretches of the chromosome that do not have any VCF entries (for example, centromeres) will be interpreted as homozygous recessive.
8578 smcpp.commands.vcf2smc INFO Population 1:
8578 smcpp.commands.vcf2smc INFO Distinguished lineages: RUSP1:0, RUSP1:1
8578 smcpp.commands.vcf2smc INFO Undistinguished lineages: RUSP2:0, RUSP2:1
29.6Mbases [00:06, 4.55Mbases/s]
15129 smcpp.util   INFO Wrote 71836 observations
Traceback (most recent call last):
  File "/Users/sbizg1/anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.6.2.dev0+nge57e612.d20170203', 'console_scripts', 'smc++')()
  File "/Users/sbizg1/anaconda3/lib/python3.5/site-packages/smcpp/frontend/console.py", line 23, in main
    cmds[args.command].main(args)
  File "/Users/sbizg1/anaconda3/lib/python3.5/site-packages/smcpp/commands/vcf2smc.py", line 241, in main
    rw.write([contig_length - last_pos] + abnb_nonseg)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by terhorst** [comment]
It's failing because it's looking in your header for the length of contig
Chr12, however the header only has "##contig=<ID=1,length=30000000>".
Changing this to "##contig=<ID=Chr12,length=30000000>" ought to fix it.
I'll change the software to throw a more informative error message.

On Fri, Feb 24, 2017 at 8:22 AM guzhongru <notifications@github.com> wrote:

Hi Jonathan
When I using the 'smc++ vcf2smc' command, there is an error appeared. Can
you please told me how can I solve this.

Here is my vcf file

##fileformat=VCFv4.2
##source=fcGENE
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##contig=<ID=1,length=30000000>
##FILTER=<ID=PASS,Description="Passed variant FILTERs">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	RUSP10	RUSP11	RUSP12	RUSP13	RUSP14	RUSP15	RUSP16	RUSP17	RUSP18	RUSP19	RUSP1	RUSP20RUSP21	RUSP22	RUSP23	RUSP24	RUSP25	RUSP26	RUSP27	RUSP28	RUSP29	RUSP2	RUSP30	RUSP3	RUSP4	RUSP5	RUSP6	RUSP7	RUSP8	RUSP9
Chr12	2237	Chr12_2237	A	T	.	PASS	AF=0.55	GT	0/1	0/0	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	1/1	0/1	1/1	1/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	0/1	1/1	0/1
Chr12	2244	Chr12_2244	G	C	.	PASS	AF=0.3	GT	1/0	1/0	1/0	1/0	0/0	1/0	1/0	0/0	0/0	0/0	1/0	0/0	0/0	0/0	0/0	0/0	1/0	0/0	1/0	1/0	1/0	1/0	0/0	1/0	1/0	1/0	1/0	1/0	0/0	1/0
Chr12	2259	Chr12_2259	A	G	.	PASS	AF=0.35	GT	0/1	0/1	0/1	0/1	0/0	0/1	0/1	0/0	0/1	0/0	0/1	0/0	0/1	0/0	0/0	0/1	0/1	0/0	0/1	0/1	0/1	0/1	0/0	0/1	0/1	0/1	0/1	0/1	0/0	0/1

and then I used the 'bgzip input.vcf' and 'tabix -p vcf input.vcf.gz' build
an indexed file. But when I using the 'smc++ vcf2smc -v input.vcf.gz
input.smc.gz Chr12 RUSP1:RUSP1,RUSP2' command, an error appeared.

8578 smcpp.logging DEBUG SMC++ v1.6.2.dev0+nge57e612.d20170203
8578 smcpp.commands.vcf2smc WARNING Neither missing cutoff (-c) or
mask (-m) has been specified. This means that stretches of the
chromosome that do not have any VCF entries (for example, centromeres)
will be interpreted as homozygous recessive.
8578 smcpp.commands.vcf2smc INFO Population 1:
8578 smcpp.commands.vcf2smc INFO Distinguished lineages: RUSP1:0, RUSP1:1
8578 smcpp.commands.vcf2smc INFO Undistinguished lineages: RUSP2:0, RUSP2:1
29.6Mbases [00:06, 4.55Mbases/s]
15129 smcpp.util   INFO Wrote 71836 observations
Traceback (most recent call last):
  File "/Users/sbizg1/anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.6.2.dev0+nge57e612.d20170203',
'console_scripts', 'smc++')()
  File "/Users/sbizg1/anaconda3/lib/python3.5/site-packages/smcpp/frontend/console.py",
line 23, in main
    cmds[args.command].main(args)
  File "/Users/sbizg1/anaconda3/lib/python3.5/site-packages/smcpp/commands/vcf2smc.py",
line 241, in main
    rw.write([contig_length - last_pos] + abnb_nonseg)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/popgenmethods/smcpp/issues/8>, or mute the thread

**Comment by guzhongru** [comment]
Thanks for your reply. The problem has been solved. And another question is how to set the value of   '--theta' and '--N0'. It is mentioned that the reference effective population size. I am a little confused about this ,,, Because for now I just know the mutation rate of a reference genome. I don't know whether it can be used.
